name: server-app
services:
  web:
    image: nginx:alpine
    ports:
      - "80:8080"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - server_app

  server_app:
    container_name: server
    image: server:${APP_VERSION:-latest}
    build: ./server_app
    